### ISSUE TITLE
stopped working with recent update

### ISSUE THREAD

**Issue by ntsjsh** [sampalmer/set-default-browser#9] opened 2017-09-14 07:17 UTC
Seems some windows update broke this tool.
See attached screenshot.

![grafik](https://user-images.githubusercontent.com/18069784/30416677-6d999e46-992d-11e7-8d22-b8eca3bd75ca.png)

**Comment by sampalmer** [comment] 2017-09-14 10:28
I just did a Windows update, and it's still working on my computer. I'm using release 1.2.1 of Set Default Browser.

I'm using:
* Windows 10 Pro
* Version 1703
* OS Build 15063.608

Which version of Set Default Browser are you using? Which version of Windows are you using? Have you tried restarting your computer?

**Comment by ntsjsh** [comment] 2017-09-14 13:06
Thanks for the feedback

I'm using:
Set Default Browser in version 1.2.1
* Windows 10 Enterprise
* Version 1607
* Build 14393.1593

Can I help with some additional informations? maybe debug output?

**Comment by sampalmer** [comment] 2017-09-14 21:26
Can you please:

1. Run `SetDefaultBrowser` and show me which browsers is says you have installed
1. Tell me the exact command you're running when you get the error

Can you please try these to see if they help?

1. Restart the computer
1. Setting a *different* default browser (eg `SetDefaultBrowser "Google Chrome"` or `SetDefaultBrowser Firefox`)
1. Run `control.exe /name Microsoft.DefaultPrograms /page pageDefaultProgram\pageAdvancedSettings?pszAppName=Google%20Chrome` and send me a screenshot of the window that opens
1. Try using Set Default Browser 1.2 (rather than 1.2.1)

**Comment by sampalmer** [comment] 2017-09-29 21:06
I'm closing this issue since I can't reproduce it and don't have enough information to troubleshoot it. Feel free to open a new issue if you manage to narrow it down.

**Comment by Fma965** [comment] 2017-10-31 14:53
I'm on 1703 and also get this issue, if i run
`control.exe /name Microsoft.DefaultPrograms /page pageDefaultProgram\pageAdvancedSettings?pszAppName=Google%20Chrome` 

nothing happens, i'm administrator aswell.

**Comment by sampalmer** [comment] 2017-10-31 22:12
Hi Fma965, can you provide more details?

**Comment by Fma965** [comment] 2017-10-31 22:13
Sure. What do you want?

**Comment by sampalmer** [comment] 2017-10-31 22:14
Can you please go through my earlier comments in this issue and try the troubleshooting steps I've posted?

**Comment by Fma965** [comment] 2017-10-31 22:16
It's my work pc so won't be able to till tomorrow. (UK time) I'm a it technician so although it's a work pc I have full admin rights

**Comment by sampalmer** [comment] 2017-12-01 22:48
I'm closing this issue since I can't reproduce it and don't have enough information to troubleshoot it. Feel free to open a new issue if you manage to narrow it down.

**Closed by sampalmer** 2017-12-01 22:48 UTC
